const express = require('express')
const dbConnceted = require('./db/mongoose')
const app = express()
const env = require('dotenv').config()
const port = process.env.PORT
const mongoose = require('mongoose')
mongoose.set('strictQuery', true)
dbConnceted()
app.use(express.json())
const userRouter = require('./routes/user.js')
const adminRouter = require('./routes/admin')
const postsRouter = require('./routes/posts')
app.use(userRouter)
app.use(adminRouter)
app.use(postsRouter)
app.listen(port, () => console.log(`server running ${port}`))